# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: DEV.to Posts
on:
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          filename: assets/metrics.plugin.posts.full.svg
          token: NOT_NEEDED

          # Options
          user: Envoy-VC
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_posts: yes
          plugin_posts_limit: 3
          plugin_posts_source: dev.to
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_user: envoy_
